### ISSUE TITLE
Correct grammar mistakes and improvements to documentation

### ISSUE THREAD

**Issue by rodgeve** [SolaceProducts/solace-openshift-quickstart#15]
1) Correct various grammar errors throughout documentation
2) Provide the same list of prerequisites for both the VMR template instructions and the VMR demo-app instructions (README.md)
3) Clarify the OpenShift prerequisites required for running this example (an OpenShift deployment and an OpenShift client environment from which to run the GitHub deploy.sh script)
4) Provide instructions for connecting to the VMR in OpenShift from the Solace SolAdmin application.

**Comment by PhilippeKhalife** [comment]
All these points have been addressed in the latest release.
