### ISSUE TITLE
How to install pubsubplus on openshift version 3.7?

### ISSUE THREAD

**Issue by jjihed** [SolaceProducts/solace-openshift-quickstart#36]
Hello,
I want to installl pubsubplus in our environment but we are in OpenShift 3.7 (No helm) and we can't update OpenShift version now.
I want to now if it is possible to install pubsubplus and how ?
Thanks.

**Comment by bczoma** [comment]
Hello, we no longer officially support and test OpenShift version 3.7 mainly because of the older Kubernetes version. You can try it anyway, following the option of using OpenShift templates provided in this project: https://github.com/SolaceProducts/pubsubplus-openshift-quickstart/blob/master/docs/PubSubPlusOpenShiftDeployment.md#option-2-using-openshift-templates
Let me know how it works out.

**Comment by jjihed** [comment]
Hello,
Thanks for your quick reply.
I have this error:


*unable to recognize no matches for kind "Role" in version
"rbac.authorization.k8s.io/v1 <http://rbac.authorization.k8s.io/v1>"unable
to recognize no matches for kind "RoleBinding" in version
"rbac.authorization.k8s.io/v1 <http://rbac.authorization.k8s.io/v1>"unable
to recognize no matches for kind "StatefulSet" in version "apps/v1"*
You now what can be the error cause ?
Thanks. Regards

Le mer. 15 avr. 2020 à 11:01, Balázs Czoma <notifications@github.com> a
écrit :

**Comment by bczoma** [comment]
These APIs were possibly still in beta for 3.7. One easy try would be to edit the template and replace:
"apiVersion: apps/v1" to "apiVersion: apps/v1beta1" (1x)
"apiVersion: rbac.authorization.k8s.io/v1" to "apiVersion: rbac.authorization.k8s.io/v1beta1" (2x)

As a second try, additionally remove these lines:
https://github.com/SolaceProducts/pubsubplus-openshift-quickstart/blob/master/templates/eventbroker_ha_template.yaml#L570-L573

Unfortunately if these don't help then it would be necessary to back out a lot of complex changes added later...

**Comment by bczoma** [comment]
I'm suggesting to close this issue.

**Comment by jjihed** [comment]
Thanks @bczoma for your great help.
