### ISSUE TITLE
Running VMR on Kubernetes

### ISSUE THREAD

**Issue by baluyot** [SolaceProducts/solace-openshift-quickstart#4]
Hi,

Tried running VMR 8.3.0.1004-enterprise on Kubernetes v1.7.1 using deployment information in your yaml example. I have also attached my own deployment yaml. Every time I tried to deploy it the status would go into Error and eventually to CrashLoopBackOff. I made sure my node has enough resources 6GB RAM and 100GB disk. Is there something I'm doing wrong? Thanks.

[solace-deployment.txt](https://github.com/SolaceLabs/solace-openshift-quickstart/files/1185725/solace-deployment.txt)

**Comment by bczoma** [comment]
There have been a lot of updates, please retry with latest and raise an issue if still running into problems. Suggesting to close this one.
