### ISSUE TITLE
Doc: Expose console and protocol access outside the cluster

### ISSUE THREAD

**Issue by lbroudoux** [SolaceProducts/solace-openshift-quickstart#45]
Hi! 

I followed this quickstart and succeeded installing a standalone event broker. However, I struggled finding how to access it from outside the cluster ...

I created some routes on my own:

* To access the management console:
```
oc create route edge solace-pubsubplus --service=my-release-pubsubplus --port=tcp-semp 
```
and then retrieve the URL to use in your browser with:
```
oc get route solace-pubsubplus -o template --template='{{.spec.host}}'
```

* To access WebSocket connector and then success using the **Try Me!** feature from console:
```
oc create route edge ws-solace-pubsubplus --service my-release-pubsubplus --port tcp-web  
```
and then retrieve the URL to use in the **Try Me!** adding and `wss://` prefix and `:443` suffix:
```
oc get route ws-solace-pubsubplus -o template --template='{{.spec.host}}'
```

It would be super-nice to add those commands directly into your documentation as deployment post-operations.

Thanks!

**Comment by bczoma** [comment]
Hi @lbroudoux, thank you for the suggestion! Yes we were planning to describe OpenShift routes in a next update and will definitely take your input.

**Comment by bczoma** [comment]
This has now been documented at https://github.com/SolaceProducts/pubsubplus-openshift-quickstart/blob/master/docs/PubSubPlusOpenShiftDeployment.md#exposing-pubsub-services
